
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DIVEQ = 48;
  public static final int PLUSPLUS = 30;
  public static final int WHEN = 52;
  public static final int STRING_LITERAL = 64;
  public static final int GTEQ = 41;
  public static final int MULT = 12;
  public static final int CONST = 5;
  public static final int LTEQ = 40;
  public static final int MODEQ = 49;
  public static final int CASE = 25;
  public static final int DOUBLE = 4;
  public static final int LPAREN = 15;
  public static final int INT = 3;
  public static final int SERVO = 58;
  public static final int FOR = 27;
  public static final int MINUS = 33;
  public static final int RPAREN = 16;
  public static final int BOOLEAN_LITERAL = 62;
  public static final int OROR = 45;
  public static final int AND = 54;
  public static final int NOT = 35;
  public static final int SEMICOLON = 11;
  public static final int LT = 38;
  public static final int OR = 55;
  public static final int COMMA = 13;
  public static final int COMP = 34;
  public static final int ANDAND = 44;
  public static final int DIV = 36;
  public static final int BEGIN = 18;
  public static final int PLUSEQ = 50;
  public static final int SERVOPOSITION = 57;
  public static final int MINUSEQ = 51;
  public static final int PLUS = 32;
  public static final int NULL_LITERAL = 65;
  public static final int IF = 22;
  public static final int DOT = 10;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int MINUSMINUS = 31;
  public static final int RETURN = 29;
  public static final int error = 1;
  public static final int EQEQ = 42;
  public static final int MULTEQ = 47;
  public static final int MOD = 37;
  public static final int BREAK = 28;
  public static final int VOID = 20;
  public static final int EQ = 14;
  public static final int SWITCH = 24;
  public static final int LBRACK = 8;
  public static final int ROBOT = 56;
  public static final int COLON = 17;
  public static final int FLOATING_POINT_LITERAL = 61;
  public static final int LBRACE = 6;
  public static final int ELSE = 23;
  public static final int RBRACK = 9;
  public static final int DELAY = 59;
  public static final int WHILE = 26;
  public static final int DEFAULT = 21;
  public static final int THEN = 53;
  public static final int RBRACE = 7;
  public static final int END = 19;
  public static final int QUESTION = 46;
  public static final int GT = 39;
  public static final int NOTEQ = 43;
  public static final int IDENTIFIER = 63;
  public static final int INTEGER_LITERAL = 60;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEAN",
  "INT",
  "DOUBLE",
  "CONST",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "DOT",
  "SEMICOLON",
  "MULT",
  "COMMA",
  "EQ",
  "LPAREN",
  "RPAREN",
  "COLON",
  "BEGIN",
  "END",
  "VOID",
  "DEFAULT",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "WHILE",
  "FOR",
  "BREAK",
  "RETURN",
  "PLUSPLUS",
  "MINUSMINUS",
  "PLUS",
  "MINUS",
  "COMP",
  "NOT",
  "DIV",
  "MOD",
  "LT",
  "GT",
  "LTEQ",
  "GTEQ",
  "EQEQ",
  "NOTEQ",
  "ANDAND",
  "OROR",
  "QUESTION",
  "MULTEQ",
  "DIVEQ",
  "MODEQ",
  "PLUSEQ",
  "MINUSEQ",
  "WHEN",
  "THEN",
  "AND",
  "OR",
  "ROBOT",
  "SERVOPOSITION",
  "SERVO",
  "DELAY",
  "INTEGER_LITERAL",
  "FLOATING_POINT_LITERAL",
  "BOOLEAN_LITERAL",
  "IDENTIFIER",
  "STRING_LITERAL",
  "NULL_LITERAL"
  };
}

