// DO NOT EDIT
// Generated by JFlex 1.8.1 http://jflex.de/
// source: standalone.flex

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright (C) 1998-2018  Gerwin Klein <lsf@jflex.de>                    *
 * All rights reserved.                                                    *
 *                                                                         *
 * License: BSD                                                            *
 *                                                                         *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */


/**
   This is a small example of a standalone text substitution scanner 
   It reads a IDENTIFIER after the keyword IDENTIFIER and substitutes all occurences
   of "hello" with "hello <IDENTIFIER>!". There is a sample input file
   "sample.inp" provided in this directory 
*/

package Scanner;
import java_cup.runtime.*;
import Parser.*;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Scanner extends sym implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\0\1\1\1\2\22\0\1\1"+
    "\1\3\1\4\2\0\1\5\1\0\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\3\20"+
    "\4\21\2\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\0\1\31\1\32\1\33\1\34\1\35\1\33\1\36"+
    "\1\37\1\40\4\33\1\41\1\42\1\43\1\33\1\44"+
    "\1\45\1\46\2\33\1\47\3\33\1\50\1\51\1\52"+
    "\3\0\1\53\1\54\1\55\1\56\1\57\1\60\1\33"+
    "\1\61\1\62\1\33\1\63\1\64\1\33\1\65\1\66"+
    "\2\33\1\67\1\70\1\71\1\72\1\73\1\74\3\33"+
    "\1\75\1\76\1\77\u0182\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\2\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\11\23\1\24\1\25\13\23\1\26"+
    "\1\1\1\27\1\30\1\31\1\0\1\32\1\33\1\34"+
    "\1\35\1\36\1\0\1\1\1\0\1\37\1\40\1\41"+
    "\1\42\3\23\1\43\15\23\1\44\6\23\1\45\1\46"+
    "\2\47\1\50\1\51\1\52\1\53\1\54\1\55\2\0"+
    "\1\37\1\56\1\23\1\57\14\23\1\60\1\61\5\23"+
    "\1\47\1\0\3\23\1\62\1\63\2\23\1\64\3\23"+
    "\1\65\3\23\1\66\1\67\1\23\1\70\1\71\1\72"+
    "\1\23\1\73\1\74\2\23\1\75\2\23\1\76\3\23"+
    "\1\77\1\100\1\101\1\23\1\102\1\103\5\23\1\104";

  private static int [] zzUnpackAction() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\100\0\200\0\300\0\200\0\200\0\200\0\200"+
    "\0\200\0\u0100\0\200\0\u0140\0\u0180\0\u01c0\0\u0200\0\200"+
    "\0\200\0\u0240\0\u0280\0\u02c0\0\200\0\u0300\0\u0340\0\u0380"+
    "\0\u03c0\0\u0400\0\u0440\0\u0480\0\u04c0\0\u0500\0\200\0\200"+
    "\0\u0540\0\u0580\0\u05c0\0\u0600\0\u0640\0\u0680\0\u06c0\0\u0700"+
    "\0\u0740\0\u0780\0\u07c0\0\200\0\u0380\0\200\0\u0800\0\200"+
    "\0\u0840\0\200\0\200\0\200\0\200\0\200\0\u0880\0\u08c0"+
    "\0\u0900\0\u01c0\0\200\0\200\0\200\0\u0940\0\u0980\0\u09c0"+
    "\0\u0380\0\u0a00\0\u0a40\0\u0a80\0\u0ac0\0\u0b00\0\u0b40\0\u0b80"+
    "\0\u0bc0\0\u0c00\0\u0c40\0\u0c80\0\u0cc0\0\u0d00\0\u0380\0\u0d40"+
    "\0\u0d80\0\u0dc0\0\u0e00\0\u0e40\0\u0e80\0\200\0\200\0\u0ec0"+
    "\0\u0f00\0\200\0\200\0\200\0\200\0\200\0\200\0\u0f40"+
    "\0\u0f80\0\u0900\0\u0380\0\u0fc0\0\u0380\0\u1000\0\u1040\0\u1080"+
    "\0\u10c0\0\u1100\0\u1140\0\u1180\0\u11c0\0\u1200\0\u1240\0\u1280"+
    "\0\u12c0\0\u0380\0\u0380\0\u1300\0\u1340\0\u1380\0\u13c0\0\u1400"+
    "\0\200\0\u1440\0\u1480\0\u14c0\0\u1500\0\u0380\0\u0380\0\u1540"+
    "\0\u1580\0\u0380\0\u15c0\0\u1600\0\u1640\0\u0380\0\u1680\0\u16c0"+
    "\0\u1700\0\u0380\0\u0380\0\u1740\0\u0380\0\u0380\0\u1780\0\u17c0"+
    "\0\u0380\0\u0380\0\u1800\0\u1840\0\u0380\0\u1880\0\u18c0\0\u0380"+
    "\0\u1900\0\u1940\0\u1980\0\u0380\0\u0380\0\u0380\0\u19c0\0\u0380"+
    "\0\u0380\0\u1a00\0\u1a40\0\u1a80\0\u1ac0\0\u1b00\0\u0380";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\2\3\1\4\1\5\1\6\1\0\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\0\1\15\1\16\3\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\2\30\1\31\4\30\1\32\1\30\1\33\1\34\1\35"+
    "\1\36\1\37\1\0\1\40\1\30\1\41\1\42\1\43"+
    "\1\44\1\45\1\30\1\46\4\30\1\47\1\50\1\51"+
    "\1\30\1\52\1\53\1\54\1\55\1\56\2\57\1\0"+
    "\1\57\1\60\44\57\1\61\26\57\126\0\1\62\63\0"+
    "\1\63\13\0\1\64\65\0\1\65\11\0\1\66\62\0"+
    "\1\67\4\0\1\70\76\0\1\71\1\0\4\72\72\0"+
    "\1\71\1\0\4\17\103\0\1\73\77\0\1\74\77\0"+
    "\1\75\70\0\4\30\6\0\10\30\1\76\6\30\3\0"+
    "\22\30\1\0\1\30\20\0\4\30\6\0\4\30\1\77"+
    "\12\30\3\0\22\30\1\0\1\30\20\0\4\30\6\0"+
    "\17\30\3\0\22\30\1\0\1\30\20\0\4\30\6\0"+
    "\10\30\1\100\6\30\3\0\22\30\1\0\1\30\20\0"+
    "\4\30\6\0\13\30\1\101\3\30\3\0\22\30\1\0"+
    "\1\30\20\0\4\30\6\0\17\30\3\0\13\30\1\102"+
    "\6\30\1\0\1\30\20\0\4\30\6\0\17\30\3\0"+
    "\4\30\1\103\15\30\1\0\1\30\20\0\4\30\6\0"+
    "\6\30\1\104\10\30\3\0\22\30\1\0\1\30\20\0"+
    "\4\30\6\0\6\30\1\105\10\30\3\0\22\30\1\0"+
    "\1\30\20\0\4\30\6\0\17\30\3\0\13\30\1\106"+
    "\1\107\5\30\1\0\1\30\20\0\4\30\6\0\17\30"+
    "\3\0\1\110\12\30\1\111\6\30\1\0\1\30\20\0"+
    "\4\30\6\0\17\30\3\0\4\30\1\112\6\30\1\113"+
    "\6\30\1\0\1\30\20\0\4\30\6\0\17\30\3\0"+
    "\11\30\1\114\10\30\1\0\1\30\20\0\4\30\6\0"+
    "\17\30\3\0\1\115\12\30\1\116\6\30\1\0\1\30"+
    "\20\0\4\30\6\0\17\30\3\0\5\30\1\117\4\30"+
    "\1\120\7\30\1\0\1\30\20\0\4\30\6\0\17\30"+
    "\3\0\4\30\1\121\15\30\1\0\1\30\20\0\4\30"+
    "\6\0\17\30\3\0\21\30\1\122\1\0\1\30\20\0"+
    "\4\30\6\0\17\30\3\0\14\30\1\123\5\30\1\0"+
    "\1\30\20\0\4\30\6\0\17\30\3\0\13\30\1\124"+
    "\6\30\1\0\1\30\20\0\4\30\6\0\17\30\3\0"+
    "\6\30\1\125\13\30\1\0\1\30\1\0\2\57\1\0"+
    "\1\57\1\0\44\57\1\0\26\57\4\0\1\126\1\0"+
    "\1\127\10\0\2\130\1\131\27\0\1\132\2\0\1\133"+
    "\3\0\1\134\4\0\1\135\1\0\1\136\1\0\1\137"+
    "\6\0\11\140\1\141\66\140\2\70\1\3\75\70\17\0"+
    "\4\142\74\0\4\30\6\0\3\30\1\143\13\30\3\0"+
    "\22\30\1\0\1\30\20\0\4\30\6\0\5\30\1\144"+
    "\11\30\3\0\22\30\1\0\1\30\20\0\4\30\6\0"+
    "\3\30\1\145\13\30\3\0\22\30\1\0\1\30\20\0"+
    "\4\30\6\0\17\30\3\0\1\30\1\146\20\30\1\0"+
    "\1\30\20\0\4\30\6\0\17\30\3\0\14\30\1\147"+
    "\5\30\1\0\1\30\20\0\4\30\6\0\4\30\1\150"+
    "\12\30\3\0\22\30\1\0\1\30\20\0\4\30\6\0"+
    "\4\30\1\151\12\30\3\0\22\30\1\0\1\30\20\0"+
    "\4\30\6\0\17\30\3\0\13\30\1\152\6\30\1\0"+
    "\1\30\20\0\4\30\6\0\17\30\3\0\4\30\1\153"+
    "\15\30\1\0\1\30\20\0\4\30\6\0\17\30\3\0"+
    "\15\30\1\154\4\30\1\0\1\30\20\0\4\30\6\0"+
    "\17\30\3\0\12\30\1\155\7\30\1\0\1\30\20\0"+
    "\4\30\6\0\17\30\3\0\5\30\1\156\14\30\1\0"+
    "\1\30\20\0\4\30\6\0\17\30\3\0\17\30\1\157"+
    "\2\30\1\0\1\30\20\0\4\30\6\0\17\30\3\0"+
    "\15\30\1\160\4\30\1\0\1\30\20\0\4\30\6\0"+
    "\17\30\3\0\11\30\1\161\10\30\1\0\1\30\20\0"+
    "\4\30\6\0\17\30\3\0\14\30\1\162\5\30\1\0"+
    "\1\30\20\0\4\30\6\0\17\30\3\0\16\30\1\163"+
    "\3\30\1\0\1\30\20\0\4\30\6\0\17\30\3\0"+
    "\16\30\1\164\3\30\1\0\1\30\20\0\4\30\6\0"+
    "\17\30\3\0\7\30\1\165\12\30\1\0\1\30\20\0"+
    "\4\30\6\0\17\30\3\0\17\30\1\166\2\30\1\0"+
    "\1\30\20\0\4\30\6\0\17\30\3\0\7\30\1\167"+
    "\12\30\1\0\1\30\20\0\4\30\6\0\17\30\3\0"+
    "\7\30\1\170\12\30\1\0\1\30\20\0\3\131\75\0"+
    "\3\171\56\0\11\140\1\172\66\140\11\0\1\141\4\0"+
    "\1\3\100\0\4\30\6\0\7\30\1\173\7\30\3\0"+
    "\22\30\1\0\1\30\20\0\4\30\6\0\17\30\3\0"+
    "\13\30\1\174\6\30\1\0\1\30\20\0\4\30\6\0"+
    "\17\30\3\0\20\30\1\175\1\30\1\0\1\30\20\0"+
    "\4\30\6\0\10\30\1\176\6\30\3\0\22\30\1\0"+
    "\1\30\20\0\4\30\6\0\10\30\1\177\6\30\3\0"+
    "\22\30\1\0\1\30\20\0\4\30\6\0\17\30\3\0"+
    "\11\30\1\200\10\30\1\0\1\30\20\0\4\30\6\0"+
    "\17\30\3\0\1\201\21\30\1\0\1\30\20\0\4\30"+
    "\6\0\17\30\3\0\4\30\1\202\15\30\1\0\1\30"+
    "\20\0\4\30\6\0\17\30\3\0\15\30\1\203\4\30"+
    "\1\0\1\30\20\0\4\30\6\0\17\30\3\0\1\204"+
    "\21\30\1\0\1\30\20\0\4\30\6\0\17\30\3\0"+
    "\1\30\1\205\20\30\1\0\1\30\20\0\4\30\6\0"+
    "\17\30\3\0\4\30\1\206\15\30\1\0\1\30\20\0"+
    "\4\30\6\0\17\30\3\0\15\30\1\207\4\30\1\0"+
    "\1\30\20\0\4\30\6\0\17\30\3\0\17\30\1\210"+
    "\2\30\1\0\1\30\20\0\4\30\6\0\17\30\3\0"+
    "\16\30\1\211\3\30\1\0\1\30\20\0\4\30\6\0"+
    "\17\30\3\0\4\30\1\212\15\30\1\0\1\30\20\0"+
    "\4\30\6\0\17\30\3\0\3\30\1\213\16\30\1\0"+
    "\1\30\20\0\4\30\6\0\17\30\3\0\11\30\1\214"+
    "\10\30\1\0\1\30\1\0\11\140\1\172\4\140\1\3"+
    "\61\140\17\0\4\30\6\0\10\30\1\215\6\30\3\0"+
    "\22\30\1\0\1\30\20\0\4\30\6\0\17\30\3\0"+
    "\16\30\1\216\3\30\1\0\1\30\20\0\4\30\6\0"+
    "\17\30\3\0\13\30\1\217\6\30\1\0\1\30\20\0"+
    "\4\30\6\0\17\30\3\0\4\30\1\220\15\30\1\0"+
    "\1\30\20\0\4\30\6\0\17\30\3\0\10\30\1\221"+
    "\11\30\1\0\1\30\20\0\4\30\6\0\17\30\3\0"+
    "\16\30\1\222\3\30\1\0\1\30\20\0\4\30\6\0"+
    "\17\30\3\0\17\30\1\223\2\30\1\0\1\30\20\0"+
    "\4\30\6\0\17\30\3\0\11\30\1\224\10\30\1\0"+
    "\1\30\20\0\4\30\6\0\17\30\3\0\4\30\1\225"+
    "\15\30\1\0\1\30\20\0\4\30\6\0\17\30\3\0"+
    "\14\30\1\226\5\30\1\0\1\30\20\0\4\30\6\0"+
    "\17\30\3\0\2\30\1\227\17\30\1\0\1\30\20\0"+
    "\4\30\6\0\17\30\3\0\4\30\1\230\15\30\1\0"+
    "\1\30\20\0\4\30\6\0\12\30\1\231\4\30\3\0"+
    "\22\30\1\0\1\30\20\0\4\30\6\0\17\30\3\0"+
    "\1\232\21\30\1\0\1\30\20\0\4\30\6\0\17\30"+
    "\3\0\11\30\1\233\10\30\1\0\1\30\20\0\4\30"+
    "\6\0\17\30\3\0\4\30\1\234\15\30\1\0\1\30"+
    "\20\0\4\30\6\0\17\30\3\0\12\30\1\235\7\30"+
    "\1\0\1\30\20\0\4\30\6\0\17\30\3\0\6\30"+
    "\1\236\13\30\1\0\1\30\20\0\4\30\6\0\17\30"+
    "\3\0\13\30\1\237\6\30\1\0\1\30\20\0\4\30"+
    "\6\0\17\30\3\0\12\30\1\240\7\30\1\0\1\30"+
    "\20\0\4\30\6\0\17\30\3\0\16\30\1\241\3\30"+
    "\1\0\1\30\20\0\4\30\6\0\17\30\3\0\15\30"+
    "\1\242\4\30\1\0\1\30\20\0\4\30\6\0\17\30"+
    "\3\0\7\30\1\243\12\30\1\0\1\30\20\0\4\30"+
    "\6\0\17\30\3\0\16\30\1\244\3\30\1\0\1\30"+
    "\20\0\4\30\6\0\17\30\3\0\7\30\1\245\12\30"+
    "\1\0\1\30\20\0\4\30\6\0\17\30\3\0\13\30"+
    "\1\246\6\30\1\0\1\30\20\0\4\30\6\0\17\30"+
    "\3\0\12\30\1\247\7\30\1\0\1\30\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6976];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\5\11\1\1\1\11\4\1\2\11"+
    "\3\1\1\11\11\1\2\11\13\1\1\11\1\1\1\11"+
    "\1\1\1\11\1\0\5\11\1\0\1\1\1\0\1\1"+
    "\3\11\30\1\2\11\2\1\6\11\2\0\27\1\1\11"+
    "\1\0\55\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

    StringBuilder string = new StringBuilder();

    private Symbol symbol(int type) {
        return new JavaSymbol(type, yyline+1, yycolumn+1);
      }
      private Symbol symbol(int type, Object value) {
        return new JavaSymbol(type, yyline+1, yycolumn+1, value);
      }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { /* ignore */
            }
            // fall through
          case 69: break;
          case 2:
            { return symbol(NOT);
            }
            // fall through
          case 70: break;
          case 3:
            { yybegin(STRING); string.setLength(0);
            }
            // fall through
          case 71: break;
          case 4:
            { return symbol(MOD);
            }
            // fall through
          case 72: break;
          case 5:
            { return symbol(LPAREN);
            }
            // fall through
          case 73: break;
          case 6:
            { return symbol(RPAREN);
            }
            // fall through
          case 74: break;
          case 7:
            { return symbol(MULT);
            }
            // fall through
          case 75: break;
          case 8:
            { return symbol(PLUS);
            }
            // fall through
          case 76: break;
          case 9:
            { return symbol(COMMA);
            }
            // fall through
          case 77: break;
          case 10:
            { return symbol(MINUS);
            }
            // fall through
          case 78: break;
          case 11:
            { return symbol(DIV);
            }
            // fall through
          case 79: break;
          case 12:
            { return symbol(INTEGER_LITERAL, Integer.valueOf(yytext()));
            }
            // fall through
          case 80: break;
          case 13:
            { return symbol(COLON);
            }
            // fall through
          case 81: break;
          case 14:
            { return symbol(SEMICOLON);
            }
            // fall through
          case 82: break;
          case 15:
            { return symbol(LT);
            }
            // fall through
          case 83: break;
          case 16:
            { return symbol(EQ);
            }
            // fall through
          case 84: break;
          case 17:
            { return symbol(GT);
            }
            // fall through
          case 85: break;
          case 18:
            { return symbol(QUESTION);
            }
            // fall through
          case 86: break;
          case 19:
            { return symbol(IDENTIFIER, yytext());
            }
            // fall through
          case 87: break;
          case 20:
            { return symbol(LBRACK);
            }
            // fall through
          case 88: break;
          case 21:
            { return symbol(RBRACK);
            }
            // fall through
          case 89: break;
          case 22:
            { return symbol(LBRACE);
            }
            // fall through
          case 90: break;
          case 23:
            { return symbol(RBRACE);
            }
            // fall through
          case 91: break;
          case 24:
            { string.append( yytext() );
            }
            // fall through
          case 92: break;
          case 25:
            { yybegin(YYINITIAL); return symbol(STRING_LITERAL, string.toString());
            }
            // fall through
          case 93: break;
          case 26:
            { return symbol(NOTEQ);
            }
            // fall through
          case 94: break;
          case 27:
            { return symbol(PLUSPLUS);
            }
            // fall through
          case 95: break;
          case 28:
            { return symbol(PLUSEQ);
            }
            // fall through
          case 96: break;
          case 29:
            { return symbol(MINUSMINUS);
            }
            // fall through
          case 97: break;
          case 30:
            { return symbol(MINUSEQ);
            }
            // fall through
          case 98: break;
          case 31:
            { return symbol(FLOATING_POINT_LITERAL, new Double(yytext()));
            }
            // fall through
          case 99: break;
          case 32:
            { return symbol(LTEQ);
            }
            // fall through
          case 100: break;
          case 33:
            { return symbol(EQEQ);
            }
            // fall through
          case 101: break;
          case 34:
            { return symbol(GTEQ);
            }
            // fall through
          case 102: break;
          case 35:
            { return symbol(OROR);
            }
            // fall through
          case 103: break;
          case 36:
            { return symbol(IF);
            }
            // fall through
          case 104: break;
          case 37:
            { string.append( '\"' );
            }
            // fall through
          case 105: break;
          case 38:
            { string.append( '\'' );
            }
            // fall through
          case 106: break;
          case 39:
            { char val = (char) Integer.parseInt(yytext().substring(1),8);
                                       string.append( val );
            }
            // fall through
          case 107: break;
          case 40:
            { string.append( '\\' );
            }
            // fall through
          case 108: break;
          case 41:
            { string.append( '\b' );
            }
            // fall through
          case 109: break;
          case 42:
            { string.append( '\f' );
            }
            // fall through
          case 110: break;
          case 43:
            { string.append( '\n' );
            }
            // fall through
          case 111: break;
          case 44:
            { string.append( '\r' );
            }
            // fall through
          case 112: break;
          case 45:
            { string.append( '\t' );
            }
            // fall through
          case 113: break;
          case 46:
            { return symbol(ANDAND);
            }
            // fall through
          case 114: break;
          case 47:
            { return symbol(END);
            }
            // fall through
          case 115: break;
          case 48:
            { return symbol(FOR);
            }
            // fall through
          case 116: break;
          case 49:
            { return symbol(INT);
            }
            // fall through
          case 117: break;
          case 50:
            { return symbol(THEN);
            }
            // fall through
          case 118: break;
          case 51:
            { return symbol(WHEN);
            }
            // fall through
          case 119: break;
          case 52:
            { return symbol(CASE);
            }
            // fall through
          case 120: break;
          case 53:
            { return symbol(ELSE);
            }
            // fall through
          case 121: break;
          case 54:
            { return symbol(BOOLEAN_LITERAL, true);
            }
            // fall through
          case 122: break;
          case 55:
            { return symbol(VOID);
            }
            // fall through
          case 123: break;
          case 56:
            { return symbol(BEGIN);
            }
            // fall through
          case 124: break;
          case 57:
            { return symbol(ROBOT);
            }
            // fall through
          case 125: break;
          case 58:
            { return symbol(SERVO);
            }
            // fall through
          case 126: break;
          case 59:
            { return symbol(BREAK);
            }
            // fall through
          case 127: break;
          case 60:
            { return symbol(CONST);
            }
            // fall through
          case 128: break;
          case 61:
            { return symbol(BOOLEAN_LITERAL, false);
            }
            // fall through
          case 129: break;
          case 62:
            { return symbol(WHILE);
            }
            // fall through
          case 130: break;
          case 63:
            { return symbol(DOUBLE);
            }
            // fall through
          case 131: break;
          case 64:
            { return symbol(RETURN);
            }
            // fall through
          case 132: break;
          case 65:
            { return symbol(SWITCH);
            }
            // fall through
          case 133: break;
          case 66:
            { return symbol(BOOLEAN);
            }
            // fall through
          case 134: break;
          case 67:
            { return symbol(DEFAULT);
            }
            // fall through
          case 135: break;
          case 68:
            { return symbol(SERVOPOSITION);
            }
            // fall through
          case 136: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   */
  private static String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = sym.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Scanner [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Scanner scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Scanner(reader);
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
